### ISSUE TITLE
Fatal error: Cannot read property 'exit' of undefined

### ISSUE THREAD

**Issue by treaz** [mradcliffe/grunt-crawl#8]
I've just installed grunt-crawl in my project and I have the following configuration

```crawl: {
            "sitemap": {
                "sitemap": true,
                "sitemapDir": "www"
            }
        }```

When I run ```grunt crawl``` I get the error:
```Running "crawl:sitemap" (crawl) task
Fatal error: Cannot read property 'exit' of undefined```

Any ideas why this is happening? I'd gladly provide more information, but I don't know how to debug grunt tasks yet.

**Comment by mradcliffe** [comment]
Hi, sorry for not responding earlier this week.

The configuration is not what it needs to be. Let's say I want to crawl (a non-angular) site "http://example.com" and generate a site map. I need to provide the task with a "target", and then the options for that target. 

This configuration should crawl up to 4 links deep into the site. It is a little slow because of the wait delays.

```javascript
  grunt.initConfig({
    crawl: {
      mytarget: {
        options: {
          baseUrl: "http://example.com",
          content: false,
          sitemap: true,
          sitemapDir: "www"
        }
      }
    }
  });
```

**Comment by treaz** [comment]
Hello,

thanks for getting back at this. I had given up hope of using this.
the configuration that I used is from the website: https://github.com/mradcliffe/grunt-crawl#sitemap
So, maybe it needs an update.

Regarding the configuration that you recommend, still didn't work (same error as before).

**Comment by mradcliffe** [comment]
Do you have [PhantomJS](http://phantomjs.org/) installed?
